# Site settings
title: jdbd.nz
description: > # this means to ignore newlines until "baseurl:"
  An average developer documents his foray into design and business.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jdbd.nz" # the base hostname & protocol for your site
twitter_username: jdbd_nz
github_username:  jdbdean

# Build settings
markdown: kramdown
