# Site settings
title: "jdbd.nz"
baseurl: ""
description: "Write code. Make great stuff."
url: "http://jdbd.nz"
twitter_username: jdbdnz
github_username:  jdbdnz
avatar: "/images/jdbdnz.jpg"
contact_url: "mailto:jdbdean+hopefullynotspam@gmail.com"

# Build settings
markdown: kramdown
