# Site settings
title: "@jdbdnz"
description: "Full-stack web developer"
call_to_action: "Presently looking for opportunities in and around Vancouver, WA"
baseurl: ""
url: "http://jdbd.nz"
twitter_username: jdbdnz
github_username:  jdbdnz
avatar: "/images/jdbdnz.jpg"
hireurl: "/hire-me/"

# Build settings
markdown: kramdown
